version: '3'
services:
  env:
    image: "python:3.6"
    links:
      - elasticmq
    environment:
      - DEBUG=1
      - SQS_ENDPOINT=elasticmq:9324
    command: /bin/bash -c "cd /opt/human_friendly_alert; pip install -e .;human_friendly_alert runserver"
  elasticmq:
    image: "mumoshu/elasticmq:0.9.3"
