openapi: 3.0.0
info:
  title: HumanFriendlyAlert
  description: https://github.com/pistatium/human-friendly-alert
  version: 0.0.1

paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /project:
    post:
      summary: Create project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                url:
                  type: string
                slack_conf:
                  type: object
                  properties:
                    channel:
                      type: string
                    username:
                      type: string
                    icon_emoji:
                      type: string

      responses:
        '201':
          description: 'created'

  /alert:
    post:
      summary: Incomming webhook to alert messages.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                namespace:
                  type: string
                type:
                  type: string
                level:
                  type: string
                status:
                  type: string
                detail:
                  type: string
                duration:
                  type: integer
      responses:
        '200':
          description: Successfully received alert message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
